name: wings
description: "Exchange by elsan"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.6
  get: ^4.7.2
  google_fonts: ^6.2.1
  get_storage: ^2.1.1
  flutter_secure_storage: ^9.2.4
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  google_sign_in: ^6.3.0
  dio: ^5.8.0+1
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon_light.png"
  min_sdk_android: 23
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_native_splash:
  color: "#ffffff"
  image: assets/icon_light.png
  color_dark: "#000000"
  image_dark: assets/icon_dark.png
  android_12:
    image: assets/icon_light.png
    color: "#ffffff"
    image_dark: assets/icon_dark.png
    color_dark: "#000000"